### PR TITLE
Added complex 'traced bitmap' shape to address ruffle-rs/visual-tests#1

### PR DESCRIPTION
**Pull request by spikything**

### CODE REVIEW

**Comment by Herschel** [comment]
Love the choice of picture, but if possible, let's try to use an image in the public domain or with a permissive license. Sorry if this seems overly paranoid, thank you!

**Comment by spikything** [comment]
Done. Is there a test runner of some sort for these visual tests?

**Comment by Herschel** [comment]
Thank you!

**Comment by spikything** [comment]
> Thank you!

Happy to help - just wish my Rust wasn't so 'rusty', so I can't contribute there. But I did a lot of these types of graphics test cases for Adobe's 'AIR for TV' when we were hunting down odd hardware accelerated rendering defects at YouView. Let me know if there are other types of graphics operations you'd like to see test cases for?

**Pull request merged**
